### ISSUE TITLE
Get hive root with --bn

### ISSUE THREAD

**Issue by DFIR-Purim** [EricZimmerman/RECmd#56]
** RECmd version # **
2.0.0.0

**Describe the bug**
When using --kn, I can successfully use the alias "ROOT\\*" to get all keys under the root path, without the need to know the root path name in advance. However, when using --bn, "ROOT" alias does not work.
Within the hive I'm analyzing, the root path is named "CsiTool-CreateHive-{00000000-0000-0000-0000-000000000000}" and the only method in which I was successful in fetching the data I wanted was defining:
KeyPath: CsiTool-CreateHive-{00000000-0000-0000-0000-000000000000}\*

The results were:
![image](https://github.com/EricZimmerman/RECmd/assets/127298743/6fc901d0-756d-4cba-a40d-218da2b4cc1f)

**To Reproduce**
Mentioned above

**Expected behavior**
Mentioned above

**Additional context**
I hope I made sense

**Comment by EricZimmerman** [comment]
Does a wild card not work for that? A *

**Comment by EricZimmerman** [comment]
What does just

*

Do

**Comment by DFIR-Purim** [comment]
Used KeyPath: *
Got:
![image](https://github.com/EricZimmerman/RECmd/assets/127298743/7f902008-ba86-4265-aa54-f44c04cd49e1)

**Comment by EricZimmerman** [comment]
If it's in a batch file you'll have to put that single star in single quotes because yaml doesn't like it otherwise

**Comment by DFIR-Purim** [comment]
Putting a single star in single quotes only gave me details about the root path itself without detailing the keys it holds, unlike what I get when using "--kn ROOT\*"

Again, I truly appreciate your assistance with this issue!!

**Comment by DFIR-Purim** [comment]
The reason I'm doing this, is that I want to dump the keys under ROOT to CSV, and it's impossible with --kn unfortunately.

**Comment by DFIR-Purim** [comment]
Is there a way to export the keys under "ROOT\*" to CSV?

**Comment by EricZimmerman** [comment]
@AndrewRathbun have you ever tried this?

**Comment by AndrewRathbun** [comment]
> @AndrewRathbun have you ever tried this?
> 

I'll have to give this a go after hours! I'll report back

**Comment by AndrewRathbun** [comment]
Alright, sorry for the delay on this.

I made a test Batch file, `ROOTtest.reb`, as seen below:

```yaml
Description: ROOT test
Author: Andrew Rathbun
Version: 1
Id: 49ff9762-4dce-413f-928b-786daa8aec5a
Keys:
    -
        Description: ROOT Key Test - SOFTWARE
        HiveType: Software
        Category: ROOT Keys
        KeyPath: ROOT\*
        Recursive: false
        Comment: ROOT test
    -
        Description: ROOT Key Test - SYSTEM
        HiveType: SYSTEM
        Category: ROOT Keys
        KeyPath: ROOT\*
        Recursive: false
        Comment: ROOT test
    -
        Description: ROOT Key Test - SAM
        HiveType: SAM
        Category: ROOT Keys
        KeyPath: ROOT\*
        Recursive: false
        Comment: ROOT test
    -
        Description: ROOT Key Test - SECURITY
        HiveType: SECURITY
        Category: ROOT Keys
        KeyPath: ROOT\*
        Recursive: false
        Comment: ROOT test
    -
        Description: ROOT Key Test - NTUSER
        HiveType: NTUSER
        Category: ROOT Keys
        KeyPath: ROOT\*
        Recursive: false
        Comment: ROOT test
    -
        Description: ROOT Key Test - UsrClass
        HiveType: UsrClass
        Category: ROOT Keys
        KeyPath: ROOT\*
        Recursive: false
        Comment: ROOT test
```

First things first, I collected my registry hives using this KAPE command:

```
.\kape.exe --tsource C: --tdest C:\temp\RegHiveTest\tout --tflush --target RegistryHives --debug
```

and I ran this RECmd command against the aforementioned hives using the following command:

```
.\RECmd.exe -d "C:\temp\RegHiveTest\tout" --bn "C:\temp\ROOTtest.reb" --nl false --csv C:\temp\RegHiveTest
```

This resulted in what I believe to be what @DFIR-Purim is looking for:

![image](https://github.com/EricZimmerman/RECmd/assets/36825567/5a74d7f9-5881-4687-b7cd-3503ba6ca533)

Nothing beyond `ROOT\*` was grabbed using the above `ROOTtest.reb` batch file. If we want this to be in production, I can clean it up a bit and name it better, like `ROOTKeyDumpNonRecursive.reb` or similar. Thoughts?
